Added header bar text
MetaProvide/adminly_core pull request #1
Opened 2022-03-09 16:25 UTC by oliveiraigorm

2022-03-10 08:35 UTC, frozenbanana requested changes

2022-03-10 08:35 UTC, frozenbanana commented on js/adminly_core-script.js
> +    $( "#nextcloud" ).append( '<a style="color:white">Platform with Human Touch</a>' );
is it possible to retrieve the text content from config?
I see in [here](https://github.com/MetaProvide/adminly_devkit/pull/3/files)

`docker exec -u www-data -it adminly_devkit_nextcloud_1 php occ theming:config slogan "Platform with Human Touch"`

Meaning we should be able to get the slogan from our config like this:

`$slogan = $this->config->getAppValue($this->appName, 'slogan');`

2022-03-10 08:35 UTC, frozenbanana commented on js/adminly_core-script.js
> +    $( "#nextcloud" ).append( '<a style="color:white">Platform with Human Touch</a>' );
Also, I prefer not to use JQuery, vanilla JS works just as well in my opinion. I assume JQuery comes out of the box when using Nextcloud? If not then I suggest removing JQuery and sticking with vanilla.

```js
document.addEventListener('DOMContentLoaded', function () {
   document.querySelector("#nextcloud").....
});
```

2022-03-10 08:36 UTC, frozenbanana commented
- [ ] Investigate if slogan can be retrieved from config

2022-03-10 10:35 UTC, mwalbeck commented on js/adminly_core-script.js
> +    $( "#nextcloud" ).append( '<a style="color:white">Platform with Human Touch</a>' );
> Also, I prefer not to use JQuery, vanilla JS works just as well in my opinion. I assume JQuery comes out of the box when using Nextcloud? If not then I suggest removing JQuery and sticking with vanilla.

JQuery comes by default, but use of it has been deprecated, so we vanilla JS is definitely the way to go.

> is it possible to retrieve the text content from config?

The biggest issue with your suggestion is passing it a long to the JS file. It should be possible if we package up one of the new libraries with webpack, but that might be a bit overkill currently.

The theming app also has an endpoint to get the theming details, that could be an option for getting the slogan:
https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php#L376

2022-03-10 13:41 UTC, frozenbanana commented on js/adminly_core-script.js
> +    $( "#nextcloud" ).append( '<a style="color:white">Platform with Human Touch</a>' );
After discussion with @mwalbeck I think is it better to keep it like this for now and move to something more robust later if needed. But, more to vanilla JS since jQuery is deprecated.

2022-03-10 17:11 UTC, oliveiraigorm commented on js/adminly_core-script.js
> +    $( "#nextcloud" ).append( '<a style="color:white">Platform with Human Touch</a>' );
I've changed it to vanilla JS

2022-03-13 20:02 UTC, mwalbeck requested changes
Overall good.

2022-03-13 20:02 UTC, mwalbeck commented on js/adminly_core-script.js
> +    slogan.style.color = "white";
For specifying colours Nextcloud heavily relies on using CSS variables, so the colours are easy to change. So instead you can do the following:

```
slogan.style.color = "var(--color-primary-text)";
```
The variable I have chosen here is the most suitable one.

2022-03-14 11:20 UTC, mwalbeck commented on js/adminly_core-script.js
> +    slogan = document.createElement("a");
One last thing, it would make more sense to have a `span` here, since it isn't a link

2022-03-14 12:10 UTC, mwalbeck approved these changes

2022-03-14 12:11 UTC, merged