Feature/navbar header
MetaProvide/adminly_core pull request #14
Opened 2022-04-27 17:17 UTC by MartinPirate

2022-04-28 07:04 UTC, frozenbanana reviewed
Looks good to me but I will let @mwalbeck do the approval.

2022-04-28 11:20 UTC, mwalbeck requested changes
The logo and image handling is most likely also going to change, but we don't have the exact method down, so for now that part is good.

2022-04-28 11:20 UTC, mwalbeck commented on css/header_nav.css
> +	padding: 0 !important;
When resetting its more clear to use `unset` instead. For position just below unset is also more preferable as it's more predictable than revert. For both properties !important is unnecessary.

2022-04-28 11:20 UTC, mwalbeck commented on css/header_nav.css
> +#appmenu .app-icon {
It doesn't work because the icons aren't set up for it, so this can be removed.

2022-04-28 11:20 UTC, mwalbeck commented on css/header_nav.css
> +#appmenu {
The height of the header has been increased, but we also need to increase it for the app menu, so it follows along.

The min-width property of `#appmenu` should be increase to 56px as well.

And a rule for `#appmenu li a` should be added increase the height and width to 56px.

2022-04-28 11:20 UTC, mwalbeck commented on css/header_nav.css
> +	align-items: center;
If you change this to `justify-content: center;`

And add a rule for `#header .header-right` setting `flex` to 1, then the VA logo should be properly centred on the page.

2022-05-02 08:46 UTC, mwalbeck commented on css/header_nav.css
> +	min-width: 56px;
This should just be width, and then also add one for height set to 56px as well.

2022-05-02 08:46 UTC, mwalbeck commented on css/header_nav.css
> +#appmenu {
We're still missing a min-width property of 56px here

2022-05-02 08:47 UTC, mwalbeck commented on css/header_nav.css
> +	align-items: center;
This still needs doing

2022-05-03 10:18 UTC, mwalbeck approved these changes

2022-05-03 10:19 UTC, merged