Calendar view
MetaProvide/adminly_core pull request #7
Opened 2022-04-01 10:33 UTC by oliveiraigorm

2022-04-01 11:45 UTC, frozenbanana commented on js/adminly_core-script.js
> +const collide = (el1, el2) => {
if a function is returning boolean this here I would like to have the naming convension 

`isColliding(el1, el2)`

2022-04-01 11:51 UTC, frozenbanana requested changes
Have a look at the comments below.

2022-04-01 12:06 UTC, frozenbanana commented on js/adminly_core-script.js
> +	});
The hard coded DOM queryStr should be written to constants

2022-04-01 12:07 UTC, frozenbanana commented on js/adminly_core-script.js
> +	});
`const QuerySelectorEvents = "fc-timegrid-event-harness fc-timegrid-event-harness-inset"` Perhaps

2022-04-01 14:22 UTC, oliveiraigorm commented on js/adminly_core-script.js
> +const collide = (el1, el2) => {
done

2022-04-01 21:26 UTC, frozenbanana commented on js/adminly_core-script.js
> +const overlapEvents = () => {
the function is removingOverlappingEvents right?

If so, call it `removingOverlappingEvents`

2022-04-01 21:34 UTC, frozenbanana commented on js/adminly_core-script.js
> +		"fc-timegrid-event-harness fc-timegrid-event-harness-inset";
I would like to minimize the amount of hardcoded selectors or to keep them defined together.

one option is to have small getter function for each like

```
const getEventColumns = () => document.querySelector('.fc-timegrid-col-events');
const getEventsByColumn = (column) => column.querySelector('.fc-timegrid-event-harness .fc-timegrid-event-harness-inset');
const getAppointmentColor ...
```

2022-04-01 21:40 UTC, frozenbanana commented on js/adminly_core-script.js
> +						hexAppointmentColor))
increase readability further

```
const isAppointment = (event) => getEventColor(event) === getAppointmentColor();
```

2022-04-01 21:43 UTC, frozenbanana commented on js/adminly_core-script.js
> +			else expandEventElement(event);
Now I am nit-picking but if it there is an if-else statement that can express in one liners like this I rather use ternary operation.

`isOverlappingMainEvent(event)) ? event.remove() : expandEventElement(event)`

2022-04-01 21:47 UTC, frozenbanana requested changes
See comments above. 

Also it looks like you are using a formatter but why is there sometimes no newlines between functions definitions?

Make sure it is consistent with 1 newline between definitions (as I think prettier has by default)

2022-04-01 21:55 UTC, frozenbanana commented on js/adminly_core-script.js
> +						hexAppointmentColor))
currently the check is structured like this 

`a && (b && !c) || (d && !e) `

can you abstract the logical complexity to something more like

`a || b`

2022-04-04 11:39 UTC, oliveiraigorm commented on js/adminly_core-script.js
> +const overlapEvents = () => {
done

2022-04-04 11:42 UTC, oliveiraigorm commented on js/adminly_core-script.js
> +						hexAppointmentColor))
Changed it to
```
isAppointment(event) &&
		(isOverlappingMainEvent(event, event.nextSibling) ||
			isOverlappingMainEvent(event, event.previousSibling))
```

2022-04-04 11:44 UTC, oliveiraigorm commented
@frozenbanana @mwalbeck  Another improvement that I can it to move the functions related to the calendar view to another file since new ones will be added and the current single file will be a mess.

2022-04-04 13:13 UTC, frozenbanana submitted a review, later dismissed
Bravo 👏!

2022-04-04 15:06 UTC, mwalbeck requested changes

2022-04-04 15:06 UTC, mwalbeck commented on js/adminly_core-script.js
> +			// IE
If this code is just to support IE, we can remove it. Nextcloud itself no longer supports IE, so there is no point in us trying to support it.

2022-04-04 15:06 UTC, mwalbeck commented on lib/AppInfo/Application.php
> +		Util::addStyle($this->appName, 'main');
Why is this empty CSS file being added?

2022-04-04 16:38 UTC, mwalbeck approved these changes
Very nice!

2022-04-04 17:00 UTC, merged